"""The `io.github.agitmit/structured-query-ast` MCP extension (TODO.md item 131).

Declares QueryGate's `StructuredQuery` read AST and write AST
(`InsertStatement`/`UpdateStatement`/`DeleteStatement`/`UpsertStatement`) as a
named, versioned, reverse-DNS-namespaced JSON-Schema contract under the MCP
`2026-07-28` protocol's SEP-2133 extensions framework — see
`docs/mcp_extensions/structured_query_ast.md` for the full spec, what is and
is not declared, and why.

**Hard boundary, enforced by construction, not just documented:** this module
never defines a JSON-RPC method and never intercepts `tools/call`.
`StructuredQueryAstExtension` overrides only `Extension.settings()` — it does
not override `methods()`, `tools()`, `resources()`, or `intercept_tool_call()`
(the SDK's fourth contribution point, which can wrap or short-circuit
`tools/call` itself — see `mcp.server.extension.Extension`), so
`MCPServer._apply_extension`/`_install_extension_interceptor` have nothing to
register or wrap beyond the settings dict advertised under
`ServerCapabilities.extensions["io.github.agitmit/structured-query-ast"]`.
The only way to submit a query or write against QueryGate remains `tools/call`
against `run_structured_queries`/`run_structured_writes` — the one request
pipeline. Adding a namespaced request method, or an interceptor that answers
a tool call without going through the real handler, would be a second
query-execution path beside that pipeline, the same rejection class as
`execute_sql` (CLAUDE.md non-negotiable #1) and the GraphQL decision
(`docs/PRODUCT_GUIDE.md` Decision Log, 2026-07-22) — do not add one without
that same level of explicit, recorded review.
`tests/unit/test_mcp_extensions.py::test_extension_does_not_intercept_tool_calls`
asserts this by identity against `Extension.intercept_tool_call`, not just by
reading this docstring.

The schema this extension points at is generated, never hand-written —
`generate_structured_query_ast_schema()` below is the single source of truth
both `scripts/generate_mcp_extension_schema.py` (writes the committed file)
and `tests/unit/test_mcp_extensions.py` (asserts the committed file matches a
fresh call, the same fresh-vs-committed drift-guard idea
`tests/unit/test_credential_redaction.py` uses for the credential invariant —
though that test compares in-process; see
`_generate_schema_in_fresh_interpreter`'s docstring for why this one doesn't).
This function does not itself force any pydantic rebuild — the schema it
returns is only ever generated by a standalone process (the script, or the
test's own subprocess), never from inside a long-lived server process, so
there is nothing here to force-mutate live request-validation classes as a
side effect of a library call. `mcp/tools/__init__.py`'s
`discover_and_register_tools()` is the one place a forced rebuild does run in
the actual server process, and only once, at tool-registration time — see its
own docstring for why that one is necessary.
"""

from __future__ import annotations

from typing import Any, Union

import pydantic as pyd

from mcp.server.extension import Extension
from querygate.query_ast.models import StructuredQuery
from querygate.write_ast.models import (
    DeleteStatement,
    InsertStatement,
    UpdateStatement,
    UpsertStatement,
)

#: Reverse-DNS extension identifier (SEP-2133 grammar: `vendor-prefix/name`).
#: `io.github.agitmit` mirrors the actual GitHub-hosted location of this
#: project (github.com/AGitmit/QueryGate) rather than presupposing a
#: registered domain QueryGate does not own.
STRUCTURED_QUERY_AST_EXTENSION_ID = "io.github.agitmit/structured-query-ast"

#: The extension/contract's own semver — independent of `querygate`'s own
#: package version (`pyproject.toml`). Bump when the emitted schema's shape
#: changes in a way a third-party consumer would care about.
STRUCTURED_QUERY_AST_EXTENSION_VERSION = "1.0.0"

#: Repo-relative paths advertised in the extension's settings, so a consumer
#: reading `capabilities.extensions` knows where to fetch the spec/schema
#: from a checkout or a raw GitHub URL without QueryGate having to serve them
#: over MCP itself (deliberately not exposed as an MCP resource — that would
#: be a second, redundant way to fetch static documentation, not part of the
#: contract this extension declares).
STRUCTURED_QUERY_AST_SPEC_PATH = "docs/mcp_extensions/structured_query_ast.md"
STRUCTURED_QUERY_AST_SCHEMA_PATH = "docs/mcp_extensions/structured_query_ast.schema.json"

#: The write AST's discriminated union — identical to the `Union` type
#: `api/routes.py` and `mcp/tools/write.py` already use to type a write
#: request body, so the published schema describes exactly the wire shape
#: those transports accept, not a parallel description of it.
WriteStatement = Union[InsertStatement, UpdateStatement, DeleteStatement, UpsertStatement]

_WRITE_STATEMENT_ADAPTER: pyd.TypeAdapter[Any] = pyd.TypeAdapter(WriteStatement)


def generate_structured_query_ast_schema() -> dict[str, Any]:
    """Emit the published schema fresh from the live Pydantic AST models.

    Single source of truth for both the generator script (writes
    `docs/mcp_extensions/structured_query_ast.schema.json`) and the
    conformance test (asserts the committed file matches this, unmodified).
    Never hand-edit the output file — `query_ast/models.py` and
    `write_ast/models.py` are the actual source of truth for these shapes;
    this function only serializes them.

    Deliberately does **not** force a pydantic rebuild of anything here. Both
    real callers (the standalone generator script, and the conformance
    test's own `_generate_schema_in_fresh_interpreter`) always run this in a
    brand-new interpreter, where `query_ast/models.py`'s own unforced,
    import-time `rebuild_recursive_ast_cycle()` call is already sufficient —
    repeated full-suite runs during development showed that a *shared*,
    long-lived process (many tests building their own schemas/`TypeAdapter`s
    over the same recursive model graph — `CteSpec.query`, `SetOpSpec.arms`,
    `Predicate.value_subquery`, ... all forward-reference `StructuredQuery`)
    can occasionally misattach a `$ref`'s sibling `description` between two
    such fields, but that symptom never appeared in an isolated interpreter,
    which is why callers isolate rather than this function force-rebuilding.
    Keeping the force-rebuild out of a general-purpose library function also
    avoids it becoming a live-request-path hazard if this function is ever
    called from somewhere reachable — see `mcp/tools/__init__.py`'s
    `discover_and_register_tools()` for the one place in the actual server
    process a forced rebuild does run, and why that one is safe (once, at
    tool-registration time, never per request).
    """
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": (
            "https://github.com/AGitmit/QueryGate/blob/main/" f"{STRUCTURED_QUERY_AST_SCHEMA_PATH}"
        ),
        "title": "QueryGate StructuredQuery AST",
        "extension": STRUCTURED_QUERY_AST_EXTENSION_ID,
        "version": STRUCTURED_QUERY_AST_EXTENSION_VERSION,
        "description": (
            "The read (StructuredQuery) and write (Insert/Update/Delete/Upsert) "
            "AST shapes QueryGate validates every request against. Declares a "
            "contract only — see docs/mcp_extensions/structured_query_ast.md's "
            "Non-goals section. Generated from querygate.query_ast.models and "
            "querygate.write_ast.models; do not hand-edit."
        ),
        "read": StructuredQuery.model_json_schema(),
        "write": _WRITE_STATEMENT_ADAPTER.json_schema(),
    }


class StructuredQueryAstExtension(Extension):
    """Advertises the `io.github.agitmit/structured-query-ast` contract.

    Purely descriptive: overrides only `settings()`. No tools, resources,
    JSON-RPC methods, or a `tools/call` interceptor are contributed — see
    this module's docstring for why that is a hard boundary, not an
    oversight.
    """

    identifier = STRUCTURED_QUERY_AST_EXTENSION_ID

    def settings(self) -> dict[str, Any]:
        return {
            "version": STRUCTURED_QUERY_AST_EXTENSION_VERSION,
            # Always "contract" — this extension never defines a callable
            # JSON-RPC method. See the module docstring's hard boundary.
            "kind": "contract",
            "spec": STRUCTURED_QUERY_AST_SPEC_PATH,
            "schema": STRUCTURED_QUERY_AST_SCHEMA_PATH,
        }
